export const secImages = {
  alabama: require("@/assets/images/sec/alabama.png"),
  arkansas: require("@/assets/images/sec/arkansas.png"),
  auburn: require("@/assets/images/sec/auburn.png"),
  florida: require("@/assets/images/sec/florida.png"),
  georgia: require("@/assets/images/sec/georgia.png"),
  kentucky: require("@/assets/images/sec/kentucky.png"),
  lsu: require("@/assets/images/sec/lsu.png"),
  mississippi_state: require("@/assets/images/sec/mississippi_state.png"),
  missouri: require("@/assets/images/sec/missouri.png"),
  ole_miss: require("@/assets/images/sec/ole_miss.png"),
  oklahoma: require("@/assets/images/sec/oklahoma.png"),
  south_carolina: require("@/assets/images/sec/south_carolina.png"),
  tennessee: require("@/assets/images/sec/tennessee.png"),
  texas: require("@/assets/images/sec/texas.png"),
  "texas_a&m": require("@/assets/images/sec/texas_a&m.png"),
  vanderbilt: require("@/assets/images/sec/vanderbilt.png"),
};

export const teamImages = {
  akron: require("@/assets/images/teams/akron.png"),
  alabama: require("@/assets/images/teams/alabama.png"),
  "alabama_a&m": require("@/assets/images/teams/alabama_a&m.png"),
  alcorn_state: require("@/assets/images/teams/alcorn_state.png"),
  arizona_state: require("@/assets/images/teams/arizona_state.png"),
  "arkansas-pine_bluff": require("@/assets/images/teams/arkansas-pine_bluff.png"),
  arkansas: require("@/assets/images/teams/arkansas.png"),
  auburn: require("@/assets/images/teams/auburn.png"),
  ball_state: require("@/assets/images/teams/ball_state.png"),
  boston_college: require("@/assets/images/teams/boston_college.png"),
  bowling_green: require("@/assets/images/teams/bowling_green.png"),
  buffalo: require("@/assets/images/teams/buffalo.png"),
  california: require("@/assets/images/teams/california.png"),
  chattanooga: require("@/assets/images/teams/chattanooga.png"),
  clemson: require("@/assets/images/teams/clemson.png"),
  colorado_state: require("@/assets/images/teams/colorado_state.png"),
  eastern_kentucky: require("@/assets/images/teams/eastern_kentucky.png"),
  florida: require("@/assets/images/teams/florida.png"),
  florida_state: require("@/assets/images/teams/florida_state.png"),
  furman: require("@/assets/images/teams/furman.png"),
  georgia: require("@/assets/images/teams/georgia.png"),
  georgia_southern: require("@/assets/images/teams/georgia_southern.png"),
  georgia_state: require("@/assets/images/teams/georgia_state.png"),
  georgia_tech: require("@/assets/images/teams/georgia_tech.png"),
  houston: require("@/assets/images/teams/houston.png"),
  kent_state: require("@/assets/images/teams/kent_state.png"),
  kentucky: require("@/assets/images/teams/kentucky.png"),
  louisiana_tech: require("@/assets/images/teams/louisiana_tech.png"),
  louisville: require("@/assets/images/teams/louisville.png"),
  lsu: require("@/assets/images/teams/lsu.png"),
  maine: require("@/assets/images/teams/maine.png"),
  massachusetts: require("@/assets/images/teams/massachusetts.png"),
  mcneese: require("@/assets/images/teams/mcneese.png"),
  mercer: require("@/assets/images/teams/mercer.png"),
  miami: require("@/assets/images/teams/miami.png"),
  michigan: require("@/assets/images/teams/michigan.png"),
  michigan_state: require("@/assets/images/teams/michigan_state.png"),
  middle_tennessee: require("@/assets/images/teams/middle_tennessee.png"),
  mississippi_state: require("@/assets/images/teams/mississippi_state.png"),
  missouri: require("@/assets/images/teams/missouri.png"),
  murray_state: require("@/assets/images/teams/murray_state.png"),
  nc_state: require("@/assets/images/teams/nc_state.png"),
  new_mexico: require("@/assets/images/teams/new_mexico.png"),
  new_mexico_state: require("@/assets/images/teams/new_mexico_state.png"),
  nicholls: require("@/assets/images/teams/nicholls.png"),
  notre_dame: require("@/assets/images/teams/notre_dame.png"),
  ohio: require("@/assets/images/teams/ohio.png"),
  oklahoma: require("@/assets/images/teams/oklahoma.png"),
  oklahoma_state: require("@/assets/images/teams/oklahoma_state.png"),
  old_dominion: require("@/assets/images/teams/old_dominion.png"),
  ole_miss: require("@/assets/images/teams/ole_miss.png"),
  samford: require("@/assets/images/teams/samford.png"),
  south_alabama: require("@/assets/images/teams/south_alabama.png"),
  south_carolina: require("@/assets/images/teams/south_carolina.png"),
  south_florida: require("@/assets/images/teams/south_florida.png"),
  southern_miss: require("@/assets/images/teams/southern_miss.png"),
  temple: require("@/assets/images/teams/temple.png"),
  tennessee: require("@/assets/images/teams/tennessee.png"),
  tennessee_tech: require("@/assets/images/teams/tennessee_tech.png"),
  texas: require("@/assets/images/teams/texas.png"),
  "texas_a&m": require("@/assets/images/teams/texas_a&m.png"),
  toledo: require("@/assets/images/teams/toledo.png"),
  tulane: require("@/assets/images/teams/tulane.png"),
  uab: require("@/assets/images/teams/uab.png"),
  ucf: require("@/assets/images/teams/ucf.png"),
  ucla: require("@/assets/images/teams/ucla.png"),
  ul_monroe: require("@/assets/images/teams/ul_monroe.png"),
  usc: require("@/assets/images/teams/usc.png"),
  utep: require("@/assets/images/teams/utep.png"),
  utsa: require("@/assets/images/teams/utsa.png"),
  vanderbilt: require("@/assets/images/teams/vanderbilt.png"),
  virginia_tech: require("@/assets/images/teams/virginia_tech.png"),
  wake_forest: require("@/assets/images/teams/wake_forest.png"),
  western_kentucky: require("@/assets/images/teams/western_kentucky.png"),
  wisconsin: require("@/assets/images/teams/wisconsin.png"),
  wofford: require("@/assets/images/teams/wofford.png"),
};

export type teamName =
  | "akron"
  | "alabama"
  | "alabama_a&m"
  | "alcorn_state"
  | "arizona_state"
  | "arkansas-pine_bluff"
  | "arkansas"
  | "auburn"
  | "ball_state"
  | "boston_college"
  | "bowling_green"
  | "buffalo"
  | "california"
  | "chattanooga"
  | "clemson"
  | "colorado_state"
  | "eastern_kentucky"
  | "florida"
  | "florida_state"
  | "furman"
  | "georgia"
  | "georgia_southern"
  | "georgia_state"
  | "georgia_tech"
  | "houston"
  | "kent_state"
  | "kentucky"
  | "louisiana_tech"
  | "louisville"
  | "lsu"
  | "maine"
  | "massachusetts"
  | "mcneese"
  | "mercer"
  | "miami"
  | "michigan"
  | "michigan_state"
  | "middle_tennessee"
  | "mississippi_state"
  | "missouri"
  | "murray_state"
  | "nc_state"
  | "new_mexico"
  | "new_mexico_state"
  | "nicholls"
  | "notre_dame"
  | "ohio"
  | "oklahoma"
  | "oklahoma_state"
  | "old_dominion"
  | "ole_miss"
  | "samford"
  | "south_alabama"
  | "south_carolina"
  | "south_florida"
  | "southern_miss"
  | "temple"
  | "tennessee"
  | "tennessee_tech"
  | "texas"
  | "texas_a&m"
  | "toledo"
  | "tulane"
  | "uab"
  | "ucf"
  | "ucla"
  | "ul_monroe"
  | "usc"
  | "utep"
  | "utsa"
  | "vanderbilt"
  | "virginia_tech"
  | "wake_forest"
  | "western_kentucky"
  | "wisconsin"
  | "wofford";
